"""Adding Trip model

Revision ID: fa882fa3a039
Revises: ab23dd691842
Create Date: 2023-08-20 15:50:35.366036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa882fa3a039'
down_revision: Union[str, None] = 'ab23dd691842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('start_place', sa.String(), nullable=True),
    sa.Column('destination_place', sa.String(), nullable=True),
    sa.Column('gas_cost', sa.Float(), nullable=True),
    sa.Column('miles_per_gallon', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_trips_user_id_users')),
    sa.PrimaryKeyConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    # ### end Alembic commands ###
